---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04

verifier:
  name: inspec

suites:
  - name: default
    run_list:
      - recipe[nell-workstation::default]
      - recipe[nell-workstation::terraform]
    attributes: { user: 'vagrant' }
